version: "3"
services:
  server:
    build: .
    command: python serv.py
    ports:
      - "8080:8080"
    container_name: pivasik

  client:
    build: ./client
    
    ports:
      - "80:80"
    container_name: blog-client
